// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQdEtSg8YSJ3NjCvlbbKAANp3nX4hoM1k',
    appId: '1:546269322129:web:cd1efd09546693e5949830',
    messagingSenderId: '546269322129',
    projectId: 'fir-chat-app-ae8c8',
    authDomain: 'fir-chat-app-ae8c8.firebaseapp.com',
    storageBucket: 'fir-chat-app-ae8c8.firebasestorage.app',
    measurementId: 'G-FXFZKCB7CC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBVITfSMW4aOtE3fH9ZDHJU3xstKB3DZk',
    appId: '1:546269322129:android:d01ad2c5518a7e74949830',
    messagingSenderId: '546269322129',
    projectId: 'fir-chat-app-ae8c8',
    storageBucket: 'fir-chat-app-ae8c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAla0syEh5-WmJri1v8M5Dsd8KxemM7jc8',
    appId: '1:546269322129:ios:8c3d16e86e436f27949830',
    messagingSenderId: '546269322129',
    projectId: 'fir-chat-app-ae8c8',
    storageBucket: 'fir-chat-app-ae8c8.firebasestorage.app',
    iosBundleId: 'com.example.midApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAla0syEh5-WmJri1v8M5Dsd8KxemM7jc8',
    appId: '1:546269322129:ios:8c3d16e86e436f27949830',
    messagingSenderId: '546269322129',
    projectId: 'fir-chat-app-ae8c8',
    storageBucket: 'fir-chat-app-ae8c8.firebasestorage.app',
    iosBundleId: 'com.example.midApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQdEtSg8YSJ3NjCvlbbKAANp3nX4hoM1k',
    appId: '1:546269322129:web:27c1b2ab05a803cc949830',
    messagingSenderId: '546269322129',
    projectId: 'fir-chat-app-ae8c8',
    authDomain: 'fir-chat-app-ae8c8.firebaseapp.com',
    storageBucket: 'fir-chat-app-ae8c8.firebasestorage.app',
    measurementId: 'G-D4WHS3MG38',
  );
}
